"""update student profile fields

Revision ID: dd1d9e2fd601
Revises: f600ca24e0c3
Create Date: 2026-08-10 20:13:42.672410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1d9e2fd601'
down_revision: Union[str, Sequence[str], None] = 'f600ca24e0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'profiles',
        sa.Column('age', sa.Integer(), nullable=False)
    )

    op.add_column(
        'profiles',
        sa.Column('gender', sa.String(length=50), nullable=False)
    )

    op.add_column(
        'profiles',
        sa.Column(
            'current_class_year',
            sa.String(length=100),
            nullable=False
        )
    )

    op.add_column(
        'profiles',
        sa.Column(
            'board',
            sa.String(length=150),
            nullable=False
        )
    )

    op.add_column(
        'profiles',
        sa.Column(
            'interest',
            sa.String(length=150),
            nullable=False
        )
    )

    op.add_column(
        'profiles',
        sa.Column(
            'higher_studies_abroad',
            sa.String(length=20),
            nullable=False
        )
    )

    op.alter_column(
        'profiles',
        'favorite_subject',
        existing_type=sa.VARCHAR(length=100),
        nullable=False
    )

    op.alter_column(
        'profiles',
        'technical_skills',
        existing_type=sa.TEXT(),
        nullable=False
    )

    op.alter_column(
        'profiles',
        'soft_skills',
        existing_type=sa.TEXT(),
        nullable=False
    )

    op.alter_column(
        'profiles',
        'hobbies',
        existing_type=sa.TEXT(),
        nullable=False
    )

    op.alter_column(
        'profiles',
        'career_goal_decided',
        existing_type=sa.VARCHAR(length=20),
        nullable=False
    )

    op.drop_column('profiles', 'preferred_career_field')
    op.drop_column('profiles', 'lowest_subject')
    op.drop_column('profiles', 'preferred_study_country')
    op.drop_column('profiles', 'career_interests')
    op.drop_column('profiles', 'percentage')
    op.drop_column('profiles', 'education_level')
    op.drop_column('profiles', 'highest_subject')
    op.drop_column('profiles', 'github_url')
    op.drop_column('profiles', 'board_or_university')
    op.drop_column('profiles', 'linkedin_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('board_or_university', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('github_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('highest_subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('education_level', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('percentage', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('career_interests', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('preferred_study_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('lowest_subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('preferred_career_field', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.alter_column('profiles', 'career_goal_decided',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('profiles', 'hobbies',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('profiles', 'soft_skills',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('profiles', 'technical_skills',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('profiles', 'favorite_subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('profiles', 'higher_studies_abroad')
    op.drop_column('profiles', 'interest')
    op.drop_column('profiles', 'board')
    op.drop_column('profiles', 'current_class_year')
    op.drop_column('profiles', 'gender')
    op.drop_column('profiles', 'age')
    # ### end Alembic commands ###
